'use strict';
(function loadDeps(){['js/newsData.js','js/admin_auth.js'].forEach(src=>{const s=document.createElement('script');s.src=src;document.head.appendChild(s);});})();
(function injectCSP(){const m=document.createElement('meta');m.httpEquiv='Content-Security-Policy';m.content=["default-src 'self'","script-src 'self' 'unsafe-inline'","style-src 'self' 'unsafe-inline' https://fonts.googleapis.com","font-src 'self' https://fonts.gstatic.com","img-src 'self' https: data:","connect-src 'none'","object-src 'none'","base-uri 'self'","frame-ancestors 'none'"].join('; ');document.head.prepend(m);})();
function showLogin(){document.getElementById('admin-login').style.display='flex';document.getElementById('admin-panel').style.display='none';document.getElementById('login-password').value='';document.getElementById('login-error').style.display='none';document.getElementById('login-error').textContent='';}
function showPanel(){document.getElementById('admin-login').style.display='none';document.getElementById('admin-panel').style.display='flex';renderArticlesList();}
function setLoginLoading(l){const b=document.getElementById('login-btn');b.disabled=l;b.textContent=l?'Перевірка...':'Увійти →';}
function showLoginError(msg){const el=document.getElementById('login-error');el.textContent=msg;el.style.display='block';el.parentElement.classList.add('shake');setTimeout(()=>el.parentElement.classList.remove('shake'),600);}
function switchTab(name){if(!Auth.guard()){showLogin();return;}document.querySelectorAll('.admin-tab').forEach(t=>t.style.display='none');document.querySelectorAll('.admin-nav__item').forEach(b=>b.classList.remove('admin-nav__item--active'));document.getElementById('tab-'+name).style.display='block';const n=document.querySelector('[data-tab="'+name+'"]');if(n)n.classList.add('admin-nav__item--active');}
function sanitize(s){if(typeof s!=='string')return '';return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function sanitizeURL(url){if(!url||typeof url!=='string')return '';if(!/^https?:\/\//i.test(url.trim()))return '';return sanitize(url);}
function renderArticlesList(){if(!Auth.guard()){showLogin();return;}const list=document.getElementById('admin-articles-list');const articles=NewsDB.getAll().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(!articles.length){list.innerHTML='<p class="admin-empty">Новин ще немає. Напиши першу!</p>';return;}list.innerHTML=articles.map(a=>`<div class="admin-article-row" data-id="${sanitize(a.id)}"><div class="admin-article-row__thumb" style="background-image:url('${sanitizeURL(a.cover)}')"></div><div class="admin-article-row__info"><div class="admin-article-row__meta"><span class="news-card__tag">${sanitize(a.tag)}</span><span class="admin-article-row__date">${sanitize(NewsDB.formatDate(a.date))}</span><span class="admin-badge ${a.published?'admin-badge--pub':'admin-badge--draft'}">${a.published?'Опублікована':'Чернетка'}</span></div><h3 class="admin-article-row__title">${sanitize(a.title)}</h3><p class="admin-article-row__excerpt">${sanitize(a.excerpt)}</p></div><div class="admin-article-row__actions"><a href="article.html?id=${encodeURIComponent(a.id)}" target="_blank" rel="noopener noreferrer" class="admin-btn" title="Переглянути">👁</a><button class="admin-btn" data-action="toggle" data-id="${sanitize(a.id)}">${a.published?'⏸':'▶'}</button><button class="admin-btn" data-action="edit" data-id="${sanitize(a.id)}">✏️</button><button class="admin-btn admin-btn--danger" data-action="delete" data-id="${sanitize(a.id)}">🗑</button></div></div>`).join('');list.querySelectorAll('[data-action]').forEach(btn=>{btn.addEventListener('click',()=>{if(!Auth.guard()){showLogin();return;}const id=btn.dataset.id;const action=btn.dataset.action;if(action==='edit')editArticle(id);if(action==='toggle')togglePublished(id);if(action==='delete')deleteArticle(id);});});}
let editingId=null;
function clearEditor(){if(!Auth.guard()){showLogin();return;}editingId=null;['f-id','f-title','f-tag','f-date','f-cover','f-excerpt'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});const body=document.getElementById('f-body');if(body)body.innerHTML='';document.getElementById('cover-preview').innerHTML='';document.getElementById('editor-title').textContent='Нова стаття';document.getElementById('preview-panel').style.display='none';document.getElementById('f-date').value=new Date().toISOString().slice(0,10);}
function editArticle(id){if(!Auth.guard()){showLogin();return;}const a=NewsDB.getById(id);if(!a)return;editingId=id;document.getElementById('f-id').value=id;document.getElementById('f-title').value=a.title;document.getElementById('f-tag').value=a.tag;document.getElementById('f-date').value=a.date;document.getElementById('f-cover').value=a.cover||'';document.getElementById('f-excerpt').value=a.excerpt;document.getElementById('f-body').innerHTML=a.body||'';document.getElementById('editor-title').textContent='Редагувати';updateCoverPreview(a.cover);switchTab('new');}
function updateCoverPreview(url){const el=document.getElementById('cover-preview');if(!url||!/^https?:\/\//i.test(url.trim())){el.innerHTML='';return;}const img=document.createElement('img');img.alt='Обкладинка';img.style.cssText='max-height:140px;width:auto;max-width:100%;border:1px solid #222;object-fit:cover;';img.onerror=()=>img.remove();img.src=url;el.innerHTML='';el.appendChild(img);}
function getArticleFromEditor(published=true){if(!Auth.guard()){showLogin();return null;}const title=document.getElementById('f-title').value.trim();const tag=document.getElementById('f-tag').value;const date=document.getElementById('f-date').value;const cover=document.getElementById('f-cover').value.trim();const excerpt=document.getElementById('f-excerpt').value.trim();const body=document.getElementById('f-body').innerHTML.trim();if(!title){showToast('⚠️ Вкажи заголовок');return null;}if(!tag){showToast('⚠️ Обери категорію');return null;}if(!date){showToast('⚠️ Вкажи дату');return null;}if(!excerpt){showToast('⚠️ Додай анонс');return null;}if(title.length>200){showToast('⚠️ Заголовок занадто довгий');return null;}if(excerpt.length>500){showToast('⚠️ Анонс занадто довгий');return null;}if(cover&&!/^https?:\/\//i.test(cover)){showToast('⚠️ URL обкладинки має починатись з https://');return null;}const id=editingId||NewsDB.generateId(title);return{id,title,tag,date,cover,excerpt,body,published,createdAt:new Date().toISOString()};}
function publishArticle(){if(!Auth.guard()){showLogin();return;}const a=getArticleFromEditor(true);if(!a)return;NewsDB.save(a);clearEditor();switchTab('articles');renderArticlesList();showToast('✅ Опубліковано!');}
function togglePublished(id){if(!Auth.guard()){showLogin();return;}const a=NewsDB.getById(id);if(!a)return;a.published=!a.published;NewsDB.save(a);renderArticlesList();showToast(a.published?'✅ Опубліковано':'⏸ Переведено в чернетку');}
function deleteArticle(id){if(!Auth.guard()){showLogin();return;}if(!confirm('Видалити цю статтю? Це незворотньо.'))return;NewsDB.remove(id);renderArticlesList();showToast('🗑 Видалено');}
function execFormat(action){if(!Auth.guard()){showLogin();return;}const body=document.getElementById('f-body');body.focus();switch(action){case 'h2':document.execCommand('formatBlock',false,'h2');break;case 'h3':document.execCommand('formatBlock',false,'h3');break;case 'bold':document.execCommand('bold');break;case 'italic':document.execCommand('italic');break;case 'ul':document.execCommand('insertUnorderedList');break;case 'quote':document.execCommand('formatBlock',false,'blockquote');break;case 'link':{const url=prompt('URL посилання:');if(url&&/^https?:\/\//i.test(url))document.execCommand('createLink',false,url);else if(url)showToast('⚠️ Тільки https:// посилання');break;}case 'img':{const url=prompt('URL зображення (https://...):');if(url&&/^https?:\/\//i.test(url))document.execCommand('insertHTML',false,`<img src="${sanitize(url)}" style="max-width:100%;margin:1rem 0;" alt="">`);else if(url)showToast('⚠️ Тільки https:// зображення');break;}case 'clear':if(confirm('Очистити весь текст?'))body.innerHTML='';break;}}
function showPreview(){if(!Auth.guard()){showLogin();return;}const panel=document.getElementById('preview-panel');const content=document.getElementById('preview-content');const title=document.getElementById('f-title').value||'Без заголовку';const body=document.getElementById('f-body').innerHTML;const cover=document.getElementById('f-cover').value;const tag=document.getElementById('f-tag').value;const date=document.getElementById('f-date').value;const coverHTML=(cover&&/^https?:\/\//i.test(cover))?`<img src="${sanitize(cover)}" style="width:100%;max-height:280px;object-fit:cover;margin-bottom:1.5rem;" alt="">`:'';;content.innerHTML=`${coverHTML}<div style="display:flex;gap:.75rem;align-items:center;margin-bottom:1rem;"><span class="news-card__tag">${sanitize(tag)||'Категорія'}</span><span style="font-size:12px;color:var(--color-muted);">${date?sanitize(NewsDB.formatDate(date)):''}</span></div><h1 style="font-family:var(--font-display);font-size:clamp(28px,4vw,48px);text-transform:uppercase;line-height:1;margin-bottom:1.5rem;">${sanitize(title)}</h1><div class="article-body-text">${body||'<p style="color:var(--color-muted)">Текст відсутній</p>'}</div>`;panel.style.display='flex';}
function showToast(msg){let t=document.getElementById('admin-toast');if(!t){t=document.createElement('div');t.id='admin-toast';document.body.appendChild(t);}t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3000);}
let lockoutInterval=null;
function showLockoutCountdown(){const el=document.getElementById('login-error');const btn=document.getElementById('login-btn');function update(){const left=Auth.lockoutRemainingSeconds();if(left<=0){clearInterval(lockoutInterval);el.textContent='';el.style.display='none';btn.disabled=false;btn.textContent='Увійти →';return;}el.textContent=`Забагато спроб. Зачекай ${left} сек.`;el.style.display='block';btn.disabled=true;btn.textContent=`Заблоковано (${left}с)`;}clearInterval(lockoutInterval);update();lockoutInterval=setInterval(update,1000);}
document.addEventListener('DOMContentLoaded',()=>{const waitForDeps=setInterval(()=>{if(typeof NewsDB!=='undefined'&&typeof Auth!=='undefined'){clearInterval(waitForDeps);init();}},30);});
function init(){if(Auth.isLocked()){showLogin();showLockoutCountdown();}else if(Auth.resumeSession()){showPanel();}else{showLogin();}
async function handleLogin(){if(Auth.isLocked()){showLockoutCountdown();return;}const pw=document.getElementById('login-password').value;if(!pw){showLoginError('Введи пароль');return;}setLoginLoading(true);const result=await Auth.login(pw);setLoginLoading(false);if(result.ok){showPanel();}else if(result.locked){showLockoutCountdown();}else{const left=result.attemptsLeft;showLoginError(left>0?`Невірний пароль. Залишилось спроб: ${left}`:`Забагато спроб. Зачекай ${result.remainingSec} сек.`);}}
document.getElementById('login-btn').addEventListener('click',handleLogin);
document.getElementById('login-password').addEventListener('keydown',e=>{if(e.key==='Enter')handleLogin();});
document.getElementById('login-password').setAttribute('autocomplete','off');
document.getElementById('logout-btn').addEventListener('click',()=>{Auth.logout();showLogin();});
document.querySelectorAll('.admin-nav__item').forEach(btn=>{btn.addEventListener('click',()=>switchTab(btn.dataset.tab));});
document.getElementById('new-article-btn').addEventListener('click',()=>{clearEditor();switchTab('new');});
document.getElementById('publish-btn').addEventListener('click',publishArticle);
document.getElementById('preview-btn').addEventListener('click',showPreview);
document.getElementById('close-preview').addEventListener('click',()=>{document.getElementById('preview-panel').style.display='none';});
document.getElementById('f-cover').addEventListener('input',e=>updateCoverPreview(e.target.value));
document.querySelectorAll('.editor-tool').forEach(btn=>{btn.addEventListener('click',()=>execFormat(btn.dataset.action));});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){const t=document.getElementById('tab-new');if(t&&t.style.display!=='none'){e.preventDefault();publishArticle();}}});
document.getElementById('f-date').value=new Date().toISOString().slice(0,10);
const textarea=document.getElementById('f-excerpt');const counter=document.getElementById('excerpt-counter');if(textarea&&counter){const upd=()=>{const l=textarea.value.length;counter.textContent=`${l}/500`;counter.style.color=l>450?'#cc6600':'';};textarea.addEventListener('input',upd);upd();}
let warnTimer=null;function schedWarn(){clearTimeout(warnTimer);warnTimer=setTimeout(()=>{let w=document.getElementById('session-warning');if(!w){w=document.createElement('div');w.id='session-warning';w.className='session-warning';w.textContent='⚠ Сесія закінчиться через 5 хвилин';document.body.appendChild(w);}requestAnimationFrame(()=>w.classList.add('show'));setTimeout(()=>w.classList.remove('show'),10000);},25*60*1000);}
['click','keydown'].forEach(e=>document.addEventListener(e,schedWarn,{passive:true}));schedWarn();}
